### ISSUE TITLE
Downloading 'example' package leads to a type error.

### ISSUE THREAD

**Issue by ghost** [rukai/PF_Sandbox#70]
Hey, so this is my first formal Github issue -- so excuse me if I happen to miss any crucial information; I'll be glad to expand on anything where I can. But yeah, I finally got around to compiling PF_S  and when I go to select the default 'Example' package, the bottom console is throwing me a :

> Error("invalid type: string \"0.0\", expect f32", line:0, column: 0)

I'm on upstream (alpha-417-ge9a649c).

Also, I'm not sure if this is a side-effect of this... but when I start up it's completely maxing out one of my cores on a Desktop i5 3000-series.

**Comment by rukai** [comment]
Thanks for the bug report! Its the first one I've received for PF Sandbox.

When I change structs or enums used to store fighter data I need to write an upgrader to ensure the json uses the new format. I didnt properly test the last one I wrote, resulting in the error you got.
The fix was straightforward https://github.com/rukai/PF_Sandbox/commit/036b7d01c5a2d877cac6ced64f45b0edea24322c

It should work now.

The maxing out a core thing is known and stuff needs to be reworked for it...

**Comment by ghost** [comment]
Built again, and as expected -- works. :^)
